Repository sous-chefs/firewall, pull requests merged in 2022-05, with the labels that each got.

#251 Add resources to configure firewalld via dbus
  .github/workflows/ci.yml
  Berksfile
  CHANGELOG.md
  README.md
  documentation/.gitkeep
  documentation/README.md
  documentation/resources/firewalld.md
  documentation/resources/firewalld_config.md
  documentation/resources/firewalld_helpers.md
  documentation/resources/firewalld_icmptype.md
  documentation/resources/firewalld_ipset.md
  documentation/resources/firewalld_policy.md
  documentation/resources/firewalld_service.md
  documentation/resources/firewalld_zone.md
  kitchen.yml
  libraries/helpers.rb
  libraries/helpers_firewalld_dbus.rb
  resources/firewalld.rb
  resources/firewalld_config.rb
  resources/firewalld_helpers.rb
  resources/firewalld_icmptype.rb
  resources/firewalld_ipset.rb
  resources/firewalld_policy.rb
  resources/firewalld_service.rb
  resources/firewalld_zone.rb
  test/fixtures/cookbooks/firewalld-test/metadata.rb
  test/fixtures/cookbooks/firewalld-test/recipes/default.rb
  test/integration/firewalld-dbus/inspec/firewalld-dbus_spec.rb
Labels: Feature Request, Release: Minor

#252 Various fixes for firewalld resources.
  CHANGELOG.md
  documentation/resources/firewalld_config.md
  documentation/resources/firewalld_helpers.md
  documentation/resources/firewalld_icmptype.md
  documentation/resources/firewalld_ipset.md
  documentation/resources/firewalld_policy.md
  documentation/resources/firewalld_service.md
  documentation/resources/firewalld_zone.md
  libraries/helpers.rb
  libraries/helpers_firewalld_dbus.rb
  resources/firewalld_config.rb
  resources/firewalld_helpers.rb
  resources/firewalld_icmptype.rb
  resources/firewalld_ipset.rb
  resources/firewalld_policy.rb
  resources/firewalld_service.rb
  resources/firewalld_zone.rb
  test/fixtures/cookbooks/firewalld-test/recipes/default.rb
  test/integration/firewalld-dbus/inspec/firewalld-dbus_spec.rb
Labels: Bug, Release: Major

#250 Automated PR: Standardising Files
  CHANGELOG.md
  chefignore
Labels: Release: Patch, Skip: Announcements

#254 Automated PR: Standardising Files
  CHANGELOG.md
  documentation/.gitkeep
Labels: Release: Patch, Skip: Announcements
